name: docker build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the image
      run: |
        docker buildx build --push \
          --tag nacifyas/whisper:3.0.0 \
          --tag nacifyas/whisper:ws \
          --tag nacifyas/whisper:latest \
          --platform linux/amd64,linux/arm64 .
